import { PrankThemeId } from '../types';

export interface ThemePresetDetails {
  id: PrankThemeId;
  name: string;
  nameBn: string;
  emoji: string;
  category: 'girl' | 'gaming' | 'bonus' | 'hot' | 'tech';
  badge: string;
  defaultTitle: string;
  defaultSubtitle: string;
  defaultButton: string;
  bgGradient: string;
  cardBg: string;
  accentColor: string;
  iconName: string;
  features: string[];
}

export const THEME_PRESETS: Record<PrankThemeId, ThemePresetDetails> = {
  girl_fb: {
    id: 'girl_fb',
    name: 'Cute Girl Facebook & WhatsApp',
    nameBn: 'মেয়ের ফেসবুক ও হোয়াটসঅ্যাপ আইডি',
    emoji: '👧',
    category: 'girl',
    badge: 'VERIFIED REAL PROFILE • ONLINE NOW',
    defaultTitle: 'তানিয়া আক্তার (২০) - ফ্রেন্ডশিপ ও লাইভ চ্যাট',
    defaultSubtitle: 'আমি নতুন রিয়েল ফ্রেন্ড খুঁজছি। সরাসরি আমার ফেসবুক ইনবক্স ও হোয়াটসঅ্যাপে পার্সোনাল চ্যাট এবং ভিডিও কল করতে নিচের বাটনে ক্লিক করুন!',
    defaultButton: 'সরাসরি ইনবক্সে চ্যাট করুন 💬',
    bgGradient: 'from-neutral-950 via-pink-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-pink-500/40 shadow-pink-500/10',
    accentColor: 'pink',
    iconName: 'Heart',
    features: [
      '১০০% আসল ও ভেরিফাইড ফেসবুক প্রোফাইল',
      'সরাসরি মেসেঞ্জারে ফ্রেন্ড রিকোয়েস্ট এক্সেপ্ট',
      'লাইভ ভিডিও কল ও প্রাইভেট চ্যাট আনলক',
    ],
  },
  free_diamond: {
    id: 'free_diamond',
    name: 'Free Fire / PUBG Free Diamonds',
    nameBn: 'ফ্রি ফায়ার ফ্রি ডায়মন্ড ও এলিট পাস',
    emoji: '💎',
    category: 'gaming',
    badge: 'GARENA & KRAFTON OFFICIAL AIRDROP',
    defaultTitle: 'পাও ১০,৬০০ ফ্রি ডায়মন্ড ও এলিট পাস!',
    defaultSubtitle: 'ফ্রি ফায়ার সিজন স্পেশাল মেগা এয়ারড্রপ! আপনার গেমের Player UID দিয়ে কোনো পাসওয়ার্ড ছাড়াই সরাসরি অ্যাকাউন্টে ১০,৬০০ ডায়মন্ড ইনস্ট্যান্ট নিন।',
    defaultButton: 'এখনই ফ্রি ডায়মন্ড ক্লেইম করুন 💎',
    bgGradient: 'from-neutral-950 via-cyan-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-cyan-500/40 shadow-cyan-500/10',
    accentColor: 'cyan',
    iconName: 'Flame',
    features: [
      'ইনস্ট্যান্ট প্লেয়ার UID ডায়মন্ড টপআপ',
      'কোনো আইডি পাসওয়ার্ড বা লগইন প্রয়োজন নেই',
      'ফ্রি এলিট পাস + এক্সক্লুসিভ গান স্কিন বান্ডেল',
    ],
  },
  cash_bonus: {
    id: 'cash_bonus',
    name: 'bKash & Nagad Cash Bonus',
    nameBn: 'বিকাশ/নগদ ফ্রি বোনাস (২৫০০ টাকা)',
    emoji: '💰',
    category: 'bonus',
    badge: 'BENGAL PAY 2026 FESTIVAL',
    defaultTitle: 'পাও ২৫০০ টাকা ফ্রি ক্যাশ বোনাস!',
    defaultSubtitle: 'বিকাশ ও নগদ গ্রাহকদের জন্য বিশেষ উৎসব উপহার! কোনো টাকা ক্যাশইন বা রিচার্জ করতে হবে না, সরাসরি আপনার বিকাশ বা নগদ নম্বরে ব্যালেন্স পাঠানো হবে।',
    defaultButton: 'এখনই ২৫০০ টাকা ক্যাশ তুলুন ৳',
    bgGradient: 'from-neutral-950 via-rose-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-rose-500/40 shadow-rose-500/10',
    accentColor: 'rose',
    iconName: 'Gift',
    features: [
      'সরাসরি বিকাশ ও নগদ ব্যালেন্সে ক্রেডিট',
      '১ মিনিটের মধ্যে ক্যাশ আউট সম্ভব',
      'কোনো চার্জ বা ডিপোজিট লাগবে না',
    ],
  },
  recharge: {
    id: 'recharge',
    name: 'Mobile Recharge Offer (বাংলা)',
    nameBn: 'মোবাইল রিচার্জ উৎসব (১০০০ টাকা)',
    emoji: '📱',
    category: 'bonus',
    badge: 'ঈদ ও বৈশাখী বিশেষ অফার ২০২৬',
    defaultTitle: 'পাও ১০০০ টাকা ফ্রি মোবাইল রিচার্জ!',
    defaultSubtitle: 'সকল সিমের জন্য অফার প্রযোজ্য (GP, Robi, Banglalink, Airtel, Teletalk)। কোনো টাকা লাগবে না, এখনই আপনার নম্বরে রিচার্জ নিন!',
    defaultButton: 'এখনই ১০০০ টাকা রিচার্জ নিন',
    bgGradient: 'from-neutral-950 via-emerald-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-emerald-500/30 shadow-emerald-500/10',
    accentColor: 'emerald',
    iconName: 'Smartphone',
    features: [
      '১ মিনিটের মধ্যে সরাসরি সিমে রিচার্জ',
      '১০০% ফ্রি ও কোনো চার্জ নেই',
      '৫০ জিবি ফ্রি ইন্টারনেট ডাটা বোনাস',
    ],
  },
  free_internet: {
    id: 'free_internet',
    name: '25GB Free 4G Internet',
    nameBn: '২৫ জিবি ফ্রি ইন্টারনেট ডাটা',
    emoji: '📶',
    category: 'bonus',
    badge: '4G HIGH SPEED INTERNET DROP',
    defaultTitle: 'পাও ২৫ জিবি ফ্রি ৪জি ইন্টারনেট ডাটা!',
    defaultSubtitle: 'জিপি, বাংলালিংক, রবি, এয়ারটেল ও টেলিটক গ্রাহকদের জন্য সম্পূর্ণ ফ্রি ২৫ জিবি হাই স্পিড ডাটা প্যাক। মেয়াদ ৩০ দিন।',
    defaultButton: '২৫ জিবি ফ্রি ডাটা একটিভ করুন 📶',
    bgGradient: 'from-neutral-950 via-blue-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-blue-500/40 shadow-blue-500/10',
    accentColor: 'blue',
    iconName: 'Smartphone',
    features: [
      'সকল সিমে ৩০ দিনের জন্য ২৫ জিবি ডাটা',
      'ইউটিউব, ফেসবুক ও টিকটকে আনলিমিটেড স্পিড',
      'কোনো প্যাক ফি বা রিচার্জ লাগবে না',
    ],
  },
  crush_secret: {
    id: 'crush_secret',
    name: 'Crush Secret Chat Tracker',
    nameBn: 'ক্রাশের গোপন মেসেজ ট্র্যাকার',
    emoji: '🤫',
    category: 'girl',
    badge: 'MESSENGER & WHATSAPP SPY SIMULATOR',
    defaultTitle: 'আপনার ক্রাশ কার সাথে সবচেয়ে বেশি চ্যাট করে?',
    defaultSubtitle: 'শুধু ক্রাশের নাম বা ফেসবুক আইডি দিন। সে কার সাথে ইনবক্সে রাত জেগে কথা বলে এবং ডিলিট করা মেসেজ ফাঁস হয়ে যাবে!',
    defaultButton: 'ক্রাশের গোপন চ্যাট দেখুন 🕵️‍♂️',
    bgGradient: 'from-neutral-950 via-violet-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-violet-500/40 shadow-violet-500/10',
    accentColor: 'violet',
    iconName: 'Eye',
    features: [
      'গোপন মেসেজ ও ডিলিট করা চ্যাট প্রদর্শন',
      'কার সাথে বেশি সময় কথা বলে তার তালিকা',
      'সম্পূর্ণ গোপন ও অদৃশ্য ট্র্যাকিং',
    ],
  },
  iphone_gift: {
    id: 'iphone_gift',
    name: 'iPhone 16 Pro Max Lucky Draw',
    nameBn: 'আইফোন ১৬ প্রো ম্যাক্স ফ্রি গিফট',
    emoji: '🎁',
    category: 'hot',
    badge: 'APPLE GLOBAL MEGA GIVEAWAY 2026',
    defaultTitle: 'অভিনন্দন! আপনি জিতেছেন iPhone 16 Pro Max!',
    defaultSubtitle: 'আজকের লাকি মেগা স্পিন ড্রতে আপনার মোবাইল নাম্বার ১ নম্বর গ্র্যান্ড পুরস্কার হিসেবে নির্বাচিত হয়েছে। সম্পূর্ণ ফ্রিতে হোম ডেলিভারি নিন।',
    defaultButton: 'আইফোন ১৬ প্রো ক্লেইম করুন 🎁',
    bgGradient: 'from-neutral-950 via-amber-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-amber-500/40 shadow-amber-500/10',
    accentColor: 'amber',
    iconName: 'Gift',
    features: [
      'ন্যাচারাল টাইটানিয়াম ২৫৬ জিবি এডিশন',
      'ফ্রি হোম ডেলিভারি ও ১ বছরের অ্যাপল ওয়ারেন্টি',
      'কোনো কুরিয়ার চার্জ লাগবে না',
    ],
  },
  online_income: {
    id: 'online_income',
    name: 'Daily 1500 Tk Mobile Income',
    nameBn: 'ঘরে বসে প্রতিদিন ১৫০০ টাকা আয়',
    emoji: '💵',
    category: 'hot',
    badge: 'VERIFIED DAILY WORK FROM HOME',
    defaultTitle: 'মোবাইলে ভিডিও দেখে দৈনিক ১৫০০ টাকা আয়!',
    defaultSubtitle: 'কোনো অভিজ্ঞতার প্রয়োজন নেই। ঘরে বসে মোবাইল দিয়ে প্রতিদিন ১-২ ঘণ্টা কাজ করে সরাসরি বিকাশ ও নগদ একাউন্টে পেমেন্ট বুঝে নিন।',
    defaultButton: 'আজকের ১৫০০ টাকা পেমেন্ট নিন 💰',
    bgGradient: 'from-neutral-950 via-emerald-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-emerald-500/30 shadow-emerald-500/10',
    accentColor: 'emerald',
    iconName: 'Coins',
    features: [
      'দৈনিক সরাসরি বিকাশ ও নগদ ওয়ালেটে পেমেন্ট',
      '১ ক্লিকে ফ্রি একাউন্ট ও ইনস্ট্যান্ট বোনাস',
      'কোনো ডিপোজিট বা ইনভেস্টমেন্ট লাগবে না',
    ],
  },
  viral: {
    id: 'viral',
    name: 'Viral Breaking News',
    nameBn: 'ভাইরাল ব্রেকিং নিউজ ও গোপন ভিডিও',
    emoji: '🔥',
    category: 'tech',
    badge: 'BREAKING NEWS EXCLUSIVE',
    defaultTitle: 'Leaked Footage: Mystery Revealed',
    defaultSubtitle: 'সোশ্যাল মিডিয়ায় তোলপাড় সৃষ্টি করা গোপন ভিডিওর সম্পূর্ণ দৃশ্য দেখুন। আর মাত্র ১৫ মিনিট এটি ইন্টারনেটে থাকবে।',
    defaultButton: 'পুরো আনসেন্সরড ভিডিও দেখুন 🎬',
    bgGradient: 'from-neutral-950 via-red-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-red-500/30 shadow-red-500/10',
    accentColor: 'red',
    iconName: 'Flame',
    features: [
      'হাই-স্পিড ফুল এইচডি ভিডিও প্লেয়ার',
      'কোনো সাইন-আপ বা ক্রেডিট কার্ড লাগবে না',
      'এক ঘণ্টার মধ্যে ৩.৫ মিলিয়নের বেশি ভিউ',
    ],
  },
  game: {
    id: 'game',
    name: 'AAA Game Beta Drop',
    nameBn: 'গেমিং গিভঅ্যাওয়ে ও বেটা কি',
    emoji: '🎮',
    category: 'gaming',
    badge: 'STEAM & CONSOLE VERIFIED DROP',
    defaultTitle: 'Grand Heist VI: Closed Alpha Key',
    defaultSubtitle: 'আপনার গেমার ট্যাগ নির্বাচিত হয়েছে! কী শেষ হওয়ার আগেই ৪৫ জিবি প্লেয়েবল ডেমো ও ৫০,০০০ গেম ক্রেডিট সম্পূর্ণ ফ্রিতে নামিয়ে নিন।',
    defaultButton: 'Claim Alpha Key & Play Now 🕹️',
    bgGradient: 'from-neutral-950 via-purple-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-purple-500/30 shadow-purple-500/10',
    accentColor: 'purple',
    iconName: 'Gamepad2',
    features: [
      'পিসি, পিএস৫ এবং মোবাইল ক্লাউড প্লেয়েবল',
      '১০০% ইনস্ট্যান্ট ক্লাউড প্লেয়েবল',
      'এক্সক্লুসিভ প্রি-অর্ডার ওয়েপন স্কিন',
    ],
  },
  ai: {
    id: 'ai',
    name: 'Next-Gen AI 5.0 Beta',
    nameBn: 'এআই (AI) সুপারকম্পিউটার',
    emoji: '🤖',
    category: 'tech',
    badge: 'EXCLUSIVE DEVELOPER PREVIEW',
    defaultTitle: 'GPT-5 Omni Quantum Access',
    defaultSubtitle: 'অভিনন্দন! আপনার ডিভাইসটি ১০০ গুণ দ্রুততম অটোনোমাস এআই ও আনলিমিটেড ভিডিও জেনারেশন মডেলের ভিআইপি টেস্টিংয়ের জন্য নির্বাচিত হয়েছে।',
    defaultButton: 'Get Started & Claim Free Access',
    bgGradient: 'from-slate-950 via-indigo-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-indigo-500/30 shadow-indigo-500/10',
    accentColor: 'indigo',
    iconName: 'Bot',
    features: [
      'আনলিমিটেড ৪K ভিডিও জেনারেশন',
      'জিরো-ল্যাটেন্সি ভয়েস স্ট্রিমিং',
      'এক্সক্লুসিভ আলফা এপিআই কী অন্তর্ভুক্ত',
    ],
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Sentinel Security',
    nameBn: 'সাইবার সিকিউরিটি প্রটেক্টর',
    emoji: '🛡️',
    category: 'tech',
    badge: 'CRITICAL SYSTEM OPTIMIZER',
    defaultTitle: 'Free Device Speed Booster & Shield',
    defaultSubtitle: 'আমাদের অটোমেটেড স্ক্যানার আপনার ডিভাইসে ১৪টি ব্যাকগ্রাউন্ড ভাইরাস ও ট্র্যাকার পেয়েছে যা ব্যাটারি নষ্ট করছে। ১ ক্লিকে ফোন বুস্ট করুন।',
    defaultButton: 'Boost Performance & Clean Now 🚀',
    bgGradient: 'from-neutral-950 via-cyan-950 to-neutral-950',
    cardBg: 'bg-neutral-900/80 border-cyan-500/30 shadow-cyan-500/10',
    accentColor: 'cyan',
    iconName: 'ShieldAlert',
    features: [
      'ইনস্ট্যান্ট ৪ গুণ র‍্যাম ক্লিন ও ব্যাটারি কুলিং',
      'ক্লাউড জিরো-ডে থ্রেট ব্লকার',
      'আল্ট্রা ফাস্ট ৬০FPS গেম অ্যাক্সিলারেটর',
    ],
  },
};

